# ici : configmap, secret
apiVersion: v1
kind: ConfigMap
metadata:
  name: latex-compile-config
  namespace: {{ .Values.namespace }}
data:
  FRONTEND_URL: {{ .Values.frontendUrl }}
  REDIS_HOST: {{ .Values.deployments.redis.name }}-svc
  REDIS_PORT: {{ .Values.deployments.redis.port | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: latex-compile-secret
  namespace: {{ .Values.namespace }}
type: Opaque
# a set dans le déploiement helm
stringData:
  TEST_BYPASS_SECRET: {{ .Values.bypassSecret | quote }}
---
apiVersion: v1
data:
  POSTGRES_DB: {{ .Values.POSTGRES_DB | quote }}
  POSTGRES_HOST: {{ .Values.POSTGRES_HOST | quote }}
  POSTGRES_PORT: {{ .Values.POSTGRES_PORT | quote }}
  POSTGRES_USER: {{ .Values.POSTGRES_USER | quote }}
kind: ConfigMap
metadata:
  name: latex-postgres-connection
  namespace: {{ .Values.namespace }}
---
apiVersion: v1
kind: Secret
metadata:
  name: latex-postgres-password
  namespace: {{ .Values.namespace }}
type: Opaque
# a set dans le déploiement helm
stringData:
  POSTGRES_PASSWORD: {{ .Values.postgresPassword | quote }}

---
apiVersion: v1
kind: Secret
metadata:
  name: latex-jwt-secret
  namespace: {{ .Values.namespace }}
type: Opaque
# a set dans le déploiement helm
stringData:
  JWT_SECRET: {{ .Values.jwtSecret | quote }}
  JWT_EXPIRES_IN: {{ .Values.jwtExpiresIn | quote }}
