# cf config globale du traefik k3s (Entrypoint) deploy/kubernetes/cluster/traefik-k3s-config.yaml (appliquée une seule fois)
--- 
# cf https://doc.traefik.io/traefik/reference/routing-configuration/kubernetes/gateway-api/
# cf https://kubernetes.io/docs/concepts/services-networking/gateway/
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: openlatex-gateway
  namespace: {{ .Values.namespace }}
spec:
  gatewayClassName: traefik
  # tls fait par caddy proxmox
  listeners:
  - name: http
    protocol: HTTP
    port: 8000
    hostname: {{ .Values.namespacedUrl }}
    allowedRoutes:
      namespaces:
        from: Same
--- 
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: openlatex-route
  namespace: {{ .Values.namespace }}
spec:
  parentRefs:
    - name: openlatex-gateway
      namespace: {{ .Values.namespace }}
      sectionName: http
  hostnames:
    - {{ .Values.namespacedUrl }}
  rules:
    - matches:
        - path:
            type: Exact
            value: /compile
      backendRefs:
        - name: {{ .Values.deployments.producer.name }}-svc
          port: {{ .Values.deployments.producer.port }}
    - matches:
        - path:
            type: PathPrefix
            value: /collab
      backendRefs:
        - name: {{ .Values.deployments.collabWebsocket.name }}-svc
          port: {{ .Values.deployments.collabWebsocket.port }}
    - matches:
        - path:
            type: PathPrefix
            value: /auth
        - path:
            type: PathPrefix
            value: /projects
        - path:
            type: Exact
            value: /health
      backendRefs:
        - name: {{ .Values.deployments.crudApi.name }}-svc
          port: {{ .Values.deployments.crudApi.port }}
    - matches:
        - path:
            type: PathPrefix
            value: /grafana
      backendRefs:
        - name: grafana-svc
          namespace: monitoring
          port: 3000
    - matches:
        - path:
            type: Exact
            value: /
        - path:
            type: PathPrefix
            value: /assets
      backendRefs:
        - name: {{ .Values.deployments.frontend.name }}-svc
          port: {{ .Values.deployments.frontend.port }}

# curl -v --resolve openlatex.blavogiez.fr:80:172.16.10.52 http://openlatex.blavogiez.fr/compile