apiVersion: v1
kind: ConfigMap
metadata:
  name: latex-grafana-config
  namespace: {{ .Values.namespace }}
data:
  GF_SERVER_ROOT_URL: https://{{ .Values.namespacedUrl }}/grafana
  GF_SERVER_SERVE_FROM_SUB_PATH: "true"
  GF_AUTH_ANONYMOUS_ENABLED: "true"
  GF_AUTH_ANONYMOUS_ORG_NAME: "Main Org."
  GF_AUTH_ANONYMOUS_ORG_ROLE: Viewer
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-provisioning
  namespace: {{ .Values.namespace }}
data:
  datasources/prometheus.yml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        uid: prometheus
        type: prometheus
        access: proxy
        url: http://prometheus-svc:9090
        isDefault: true
  dashboards/dashboards.yml: |
    apiVersion: 1
    providers:
      - name: openlatex
        folder: OpenLatex
        type: file
        options:
          path: /var/lib/grafana/dashboards
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-dashboards
  namespace: {{ .Values.namespace }}
data:
  compiler.json: |
{{ .Files.Get "files/grafana/compiler.json" | indent 4 }}
  account-manager.json: |
{{ .Files.Get "files/grafana/account-manager.json" | indent 4 }}
  user-saves.json: |
{{ .Files.Get "files/grafana/user-saves.json" | indent 4 }}
  k3s-instances.json: |
{{ .Files.Get "files/grafana/k3s-instances.json" | indent 4 }}