# Poc rapide, le hardening sera fait après en prenant bien le temps
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: latex-crud-api
  name: latex-crud-api
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: latex-crud-api
  strategy: {}
  template:
    metadata:
      labels:
        app: latex-crud-api
    spec:
      containers:
      - image: {{ .Values.images.crud-api }}
        name: latex-crud-api
        resources: {}
        envFrom:
          - configMapRef:
              name: latex-postgres-connection
          - secretRef:
              name: latex-postgres-password 
status: {}
--- 
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: latex-collab-websocket
  name: latex-collab-websocket
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: latex-collab-websocket
  strategy: {}
  template:
    metadata:
      labels:
        app: latex-collab-websocket
    spec:
      containers:
      - image: {{ .Values.images.collab-websocket }}
        name: latex-collab-websocket
        resources: {}
        envFrom:
          - configMapRef:
              name: latex-postgres-connection
          - secretRef:
              name: latex-postgres-password 
status: {}
--- 
# postgres todo en statefulset + PVC
