# Poc rapide, le hardening sera fait après en prenant bien le temps
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: latex-frontend
  name: latex-frontend
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: latex-frontend
  strategy: {}
  template:
    metadata:
      labels:
        app: latex-frontend
    spec:
      containers:
      - image: {{ .Values.images.latex-frontend }}
        name: latex-frontend
        resources: {}
status: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: latex-prometheus
  name: latex-prometheus
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: latex-prometheus
  strategy: {}
  template:
    metadata:
      labels:
        app: latex-prometheus
    spec:
      containers:
      - image: {{ .Values.images.latex-prometheus }}
        name: latex-prometheus
        resources: {}
status: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: latex-grafana
  name: latex-grafana
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: latex-grafana
  strategy: {}
  template:
    metadata:
      labels:
        app: latex-grafana
    spec:
      containers:
      - image: {{ .Values.images.latex-grafana }}
        name: latex-grafana
        resources: {}
status: {}