# ici : services, ingress, networkpolicy
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy 
metadata: 
  name: {{ .Values.deployments.worker.name }}-network-policy
  namespace: {{ .Values.namespace }}
spec:
  podSelector:
    matchExpressions:
      - key: app
        operator: In
        values:
          - {{ .Values.deployments.worker.name }} 
          - {{ .Values.deployments.producer.name }} 
  policyTypes:
  - Egress
  
  egress:
    - to:
        - podSelector:
            matchLabels:
              app: {{ .Values.deployments.redis.name }}
      ports:
        - protocol: TCP
          port: {{ .Values.deployments.redis.port }} 
      # on autorise le dns en sortie
    - ports:
        - protocol: TCP
          port: 53 
        - protocol: UDP
          port: 53 
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy 
metadata: 
  name: {{ .Values.deployments.redis.name }}-network-policy
  namespace: {{ .Values.namespace }}
spec:
  podSelector:
    matchLabels:
      app: {{ .Values.deployments.redis.name }} 
  policyTypes:
  - Ingress
  
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: {{ .Values.deployments.worker.name }} 
        - podSelector:
            matchLabels:
              app: {{ .Values.deployments.producer.name }} 
      ports:
        - protocol: TCP
          port: {{ .Values.deployments.redis.port }} 

          
