apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: latex-compile-ingress
  namespace: default
spec:
  ingressClassName: traefik
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: latex-compile-svc
            port:
              number: 80
