apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus-agent
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: prometheus-agent
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: prometheus-agent
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: prometheus-agent
subjects:
  - kind: ServiceAccount
    name: prometheus-agent
    namespace: default
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-agent-config
  namespace: default
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s

    scrape_configs:
      - job_name: 'k3s-compiler'
        kubernetes_sd_configs:
          - role: pod
            namespaces:
              names: ['default']
        relabel_configs:
          - source_labels: [__meta_kubernetes_pod_label_app]
            regex: latex-compile
            action: keep
          - source_labels: [__meta_kubernetes_pod_ip]
            target_label: __address__
            replacement: ${1}:9000
          - source_labels: [__meta_kubernetes_pod_name]
            target_label: pod

      - job_name: 'kube-state-metrics'
        static_configs:
          - targets: ['kube-state-metrics-svc.default.svc.cluster.local:8080']

    remote_write:
      # hostname internal AWS de l'api vps (résolu par le VPC, pas de /etc/hosts). ip privée donc pas interprétable ailleurs
      # 10.0.1.82 est donc fixée dans Terraform comme étant toujours l'ip privée de l'api vps pour être stable.
      - url: "http://ip-10-0-1-82.eu-west-3.compute.internal:9090/api/v1/write"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-agent
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus-agent
  template:
    metadata:
      labels:
        app: prometheus-agent
    spec:
      serviceAccountName: prometheus-agent
      nodeSelector:
        node-role.kubernetes.io/control-plane: "true"
      tolerations:
        - key: node-role.kubernetes.io/control-plane
          operator: Exists
          effect: NoSchedule
      containers:
        - name: prometheus
          image: prom/prometheus:v3.11.2
          args:
            - '--config.file=/etc/prometheus/prometheus.yml'
            - '--agent'
          volumeMounts:
            - name: config
              mountPath: /etc/prometheus
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 250m
              memory: 512Mi
      volumes:
        - name: config
          configMap:
            name: prometheus-agent-config
