# peut être set par le playbook / CI/CD à openlatex-prod si la branche est main
namespace: "openlatex-prod"

deployments:
  worker:
    name: worker
    image: ghcr.io/openlatex/queue-worker:latest
    envFromConfigMaps: [latex-compile-config]
    resources:
      requests:
        cpu: 400m
        memory: 200Mi
      limits:
        cpu: 1200m
        memory: 2000Mi
  producer:
    name: producer
    image: ghcr.io/openlatex/queue-producer:latest
    port: 9000
    envFromConfigMaps: [latex-compile-config]
    envFromSecrets: [latex-compile-secret]
  redis:
    name: redis
    image: redis
    port: 6379
    envFromConfigMaps: [latex-compile-config]
  crudApi:
    name: crud-api
    image: ghcr.io/openlatex/account-crud-api:latest
    port: 8000
    envFromConfigMaps: [latex-postgres-connection]
    envFromSecrets: [latex-postgres-password]
  collabWebsocket:
    name: collab-websocket
    image: ghcr.io/openlatex/collab-websocket:latest
    port: 7000
    envFromConfigMaps: [latex-postgres-connection]
    envFromSecrets: [latex-postgres-password]
  frontend:
    name: latex-frontend
    image: ghcr.io/openlatex/frontend:latest
    port: 80

POSTGRES_DB: openlatex
POSTGRES_HOST: latex-postgres
POSTGRES_PORT: 5432
POSTGRES_USER: openlatex
# sera changé / randomisé au playbook
postgresPassword: openlatex

postgresql:
  enabled: true
  fullnameOverride: latex-postgres
  architecture: standalone
  auth:
    enablePostgresUser: false
    username: openlatex
    database: openlatex
    existingSecret: latex-postgres-password
    secretKeys:
      userPasswordKey: POSTGRES_PASSWORD
  primary:
    initdb:
      scriptsConfigMap: latex-postgres-initdb
    persistence:
      enabled: true
      size: 3Gi
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 500m
        memory: 512Mi

frontendUrl: https://openlatex.github.io

# deux url différentes sur internet pour accéder aux namespaces afin d'avoir une version stable et une version test
namespacedUrl: openlatex.blavogiez.fr

# secret de contournement de la limite de compilation, utile pour les tests de charge
bypassSecret: "changeme"

hpa:
  minReplicas: 8
  maxReplicas: 20
