# peut être set par le playbook / CI/CD à openlatex-prod si la branche est main
namespace: "openlatex-dev"

# contrat de template qui regroupe les besoins simples des deployments. Il va pas trop loin dans la modularité pour pas avoir une map trop grosse
deployments:
  worker:
    name: worker
    image: ghcr.io/openlatex/queue-worker:latest
    envFromConfigMaps: [latex-compile-config]
    resources:
      requests:
        cpu: 400m
        memory: 200Mi
      limits:
        cpu: 1200m
        memory: 2000Mi
  producer:
    name: producer
    image: ghcr.io/openlatex/queue-producer:latest
    port: 9000
    envFromConfigMaps: [latex-compile-config]
    envFromSecrets: [latex-compile-secret]
  redis:
    name: redis
    image: redis
    port: 6379
    envFromConfigMaps: [latex-compile-config]
  crudApi:
    name: crud-api
    image: ghcr.io/openlatex/account-crud-api:latest
    port: 8000
    envFromConfigMaps: [latex-postgres-connection]
    envFromSecrets: [latex-postgres-password]
  collabWebsocket:
    name: collab-websocket
    image: ghcr.io/openlatex/collab-websocket:latest
    port: 7000
    envFromConfigMaps: [latex-postgres-connection]
    envFromSecrets: [latex-postgres-password]
  frontend:
    name: latex-frontend
    image: ghcr.io/openlatex/frontend:latest
    port: 80
  latexGrafana:
    name: latex-grafana
    uid: 472
    image: grafana/grafana-oss:10.4.3
    port: 3000
    envFromConfigMaps: [latex-grafana-config]
    volumeMounts:
      - name: provisioning
        mountPath: /etc/grafana/provisioning
        readOnly: true
      - name: dashboards
        mountPath: /var/lib/grafana/dashboards
        readOnly: true
    volumes:
      - name: provisioning
        configMap:
          name: grafana-provisioning
      - name: dashboards
        configMap:
          name: grafana-dashboards

prometheusAgent:
  image: prom/prometheus:v2.55.1

prometheusImage: prom/prometheus:v2.55.1

POSTGRES_DB: openlatex
POSTGRES_HOST: latex-postgres
POSTGRES_PORT: 5432
POSTGRES_USER: openlatex
# sera changé / randomisé au playbook
postgresPassword: openlatex

postgresql:
  enabled: true
  fullnameOverride: latex-postgres
  architecture: standalone
  auth:
    enablePostgresUser: false
    username: openlatex
    database: openlatex
    existingSecret: latex-postgres-password
    secretKeys:
      userPasswordKey: POSTGRES_PASSWORD
  primary:
    initdb:
      scriptsConfigMap: latex-postgres-initdb
    persistence:
      enabled: true
      size: 3Gi
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 500m
        memory: 512Mi

frontendUrl: https://openlatex.github.io
remoteWriteUrl: http://172.16.10.51:9090/api/v1/write

# deux url différentes sur internet pour accéder aux namespaces afin d'avoir une version stable et une version test
namespacedUrl: openlatex-dev.blavogiez.fr

# secret de contournement de la limite de compilation, utile pour les tests de charge
bypassSecret: "changeme"

hpa:
  minReplicas: 2
  maxReplicas: 8
