# deployer k3s sur master
# on rappelle que k3s est installé en user data de terraform
# Ce playbook tourne sur le contrôleur local et parle directement à l'API k3s. de ce fait pas besoin de config le ssh

---
- hosts: localhost
  connection: local
  gather_facts: false
  environment:
    K8S_AUTH_KUBECONFIG: "{{ lookup('env', 'KUBECONFIG') | default('./k3s.yaml') }}"
  tasks:
    - name: Déployer le manifest latex-compile (il va déployer sur les workers qui ont été joints lors du user data terraform)
      kubernetes.core.k8s:
        state: present
        src: "{{ playbook_dir }}/../../infra/kubernetes/latex-compile.yaml"

    - name: Déployer l'ingress latex-compile
      kubernetes.core.k8s:
        state: present
        src: "{{ playbook_dir }}/../../infra/kubernetes/latex-compile-ingress.yaml"

    - name: Déployer kube-state-metrics
      kubernetes.core.k8s:
        state: present
        src: "{{ playbook_dir }}/../../infra/kubernetes/kube-state-metrics.yaml"

    - name: Déployer Prometheus agent
      kubernetes.core.k8s:
        state: present
        src: "{{ playbook_dir }}/../../infra/kubernetes/prometheus-agent.yaml"

    # - name: Rollout restart pour appliquer le nouveau secret  !
    #   kubernetes.core.k8s:
    #     state: patched
    #     kind: Deployment
    #     name: latex-compile
    #     namespace: default
    #     definition:
    #       spec:
    #         template:
    #           metadata:
    #             annotations:
    #               kubectl.kubernetes.io/restartedAt: "{{ now(utc=True, fmt='%Y-%m-%dT%H:%M:%SZ') }}"

    # - name: État des pods avant attente
    #   kubernetes.core.k8s_info:
    #     kind: Pod
    #     namespace: default
    #     label_selectors:
    #       - app=latex-compile
    #   register: pods_before

    # - name: Afficher l'état des pods
    #   debug:
    #     msg: "{{ item.metadata.name }} — {{ item.status.phase }} — {{ item.status.containerStatuses | default([]) | map(attribute='state') | list }}"
    #   loop: "{{ pods_before.resources }}"

    - name: Attendre que le déploiement soit prêt
      kubernetes.core.k8s_info:
        kind: Deployment
        name: latex-compile
        namespace: default
        wait: true
        wait_condition:
          type: Available
          status: "True"
        wait_timeout: 300
