---
- hosts: all
  gather_facts: false
  vars:
    deploy_branch: "{{ lookup('env', 'DEPLOY_BRANCH') }}"
    repo_url: "{{ lookup('env', 'REPO_URL') }}"
    postgres_user: "{{ lookup('env', 'POSTGRES_USER') }}"
    postgres_password: "{{ lookup('env', 'POSTGRES_PASSWORD') }}"
    postgres_db: "{{ lookup('env', 'POSTGRES_DB') }}"
    jwt_secret: "{{ lookup('env', 'JWT_SECRET') }}"
    jwt_expires_in: "{{ lookup('env', 'JWT_EXPIRES_IN') }}"
    frontend_url: "{{ lookup('env', 'FRONTEND_URL') }}"
    resend_api_key: "{{ lookup('env', 'RESEND_API_KEY') }}"
    grafana_admin_user: "{{ lookup('env', 'GRAFANA_ADMIN_USER') }}"
    grafana_admin_password: "{{ lookup('env', 'GRAFANA_ADMIN_PASSWORD') }}"
    test_bypass_secret: "{{ lookup('env', 'TEST_BYPASS_SECRET') }}"
  tasks:
    - name: Cloner ou mettre à jour le dépôt
      ansible.builtin.git:
        repo: "{{ repo_url }}"
        dest: /home/admin/openlatex
        version: "{{ deploy_branch }}"
        force: true

    - name: Ecrire le fichier .env
      ansible.builtin.template:
        src: ../templates/backend-env.j2
        dest: /home/admin/openlatex/backend/.env
        mode: '0600'
      no_log: true

    - name: Installer le SDK Python Docker (requis par community.docker)
      ansible.builtin.apt:
        name: python3-docker
        state: present

    # le module gère l'idempotence (c'est mieux qu'un ansible builtin shell)
    - name: Déployer les conteneurs
      community.docker.docker_compose_v2:
        project_src: /home/admin/openlatex/backend
        state: present
        pull: always
        build: always
        recreate: always

    - name: Nettoyer les images inutilisées (pour eviter trop de stockage des anciennes distributions latex assez volumineuses)
      community.docker.docker_prune:
        images: true
        images_filters:
          dangling: "true"
