apiVersion: v2
name: openlatex-compile
description: Helm chart du backend de compilation OpenLaTeX
type: application
version: 0.1.2
appVersion: "1.0.0"


# on utilise le helm chart de kube state metrics pour être plus propre
dependencies:
  - name: kube-state-metrics
    version: "7.8.1"
    repository: "https://prometheus-community.github.io/helm-charts"
    condition: kube-state-metrics.enabled