enabled: true
# ce chart marche pour tout le cluster, donc namespace à part de openlatex
namespace: monitoring

replicas: 1

# namespaces applicatifs dont les métriques sont scrappées par le prometheus central
namespaces: [openlatex-dev, openlatex-prod]

prometheusImage: prom/prometheus:v2.55.1
grafanaImage: grafana/grafana-oss:10.4.3

prometheusStorageSize: 10Gi

serviceAccount:
  create: true

rbac:
  create: true