---
- hosts: all
  gather_facts: true
  vars:
    deploy_branch: "{{ lookup('env', 'DEPLOY_BRANCH') }}"
    repo_url: "{{ lookup('env', 'REPO_URL') }}"
  tasks:
    - name: Cloner ou mettre à jour le dépôt
      ansible.builtin.git:
        repo: "{{ repo_url }}"
        dest: /home/admin/openlatex
        version: "{{ deploy_branch }}"
        force: true

    - name: Injecter les variables dans le .env
      ansible.builtin.template:
        src: ../templates/backend-env.j2
        dest: /home/admin/openlatex/deploy/compose/.env
        mode: '0600'
      no_log: true

    - name: Arrêter les conteneurs pour libérer la RAM avant le pull/build
      community.docker.docker_compose_v2:
        project_src: /home/admin/openlatex/deploy/compose
        state: absent

    # le module gère l'idempotence (c'est mieux qu'un ansible builtin shell)
    - name: Déployer les conteneurs
      community.docker.docker_compose_v2:
        project_src: /home/admin/openlatex/deploy/compose
        state: present
        pull: always
        build: policy
        recreate: auto

    - name: Nettoyer les images inutilisées (pour eviter trop de stockage des anciennes distributions latex assez volumineuses)
      community.docker.docker_prune:
        images: true
        images_filters:
          dangling: "true"
