name: (DOCKER) - Construction de l'image 
# Construit l'image docker du Node.js (compilateur + gestion des comptes)

on:
  push:
    paths:
      - 'backend/**'
      - '!backend/docker-compose.yml'
      - '!backend/postgres/**'
    branches: [main, backend/release]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/openlatex-backend:latest
