name: deploiement backend docker VPS

on:
  push:
    branches: [develop-bapi]
  workflow_dispatch:

jobs:
  deploy-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: config ssh
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.VPS_SSH_KEY }}

      - name: Deploiement sur vps
        env:
          VPS_HOST: ${{ secrets.VPS_HOST }}
          VPS_USER: ${{ secrets.VPS_USER }}
        run: |
          ssh -o StrictHostKeyChecking=no $VPS_USER@$VPS_HOST << 'EOF'
            cd /home/deployer
            rm -rf OpenLatex
            git clone https://github.com/${{ github.repository }}.git OpenLatex
            cd OpenLatex/backend
            docker build -t openlatex-backend .
            docker stop openlatex-backend || true
            docker rm openlatex-backend || true
            docker run -d --name openlatex-backend -p 8000:8000 --restart unless-stopped openlatex-backend
          EOF
